@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NjFjYjhkYS1jZmIwLTQ4NmYtYTM2OS0xOGNiNGRlMGMyZWMiLCJpYXQiOjE3NTk2Nzc3MDcsImV4cCI6MTc2MDI4MjUwN30.M-Q07KN6X82HOp2lOgwZ_9d0GHgnbWScLmCfXImIvp4
@customer_token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGEzMjlhNi02ODE3LTQ0NWUtYTBmZi05NTJkOGVkZmY1YzAiLCJpYXQiOjE3NTk2Nzg1MjMsImV4cCI6MTc2MDI4MzMyM30.HTrbpWoFNl0I5Z6e2ZqcqI6QmkBH3qfMGXEcKDrnlNs

### Login as customer ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"test@gmail.com",
 "password":"test123"
}


### Login as Admin ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"admin@gmail.com",
 "password":"test123"
}


### Create a brand
POST http://localhost:8000/brand
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
    "name":"Zara",
    "description":"This is a test",
    "image_url":"test"
}


### Get all Brands ###
GET http://localhost:8000/brand

### Get a Brand ###
GET http://localhost:8000/brand/0cbed636-e7ff-44fe-8440-f186bf1a7e25


### Update a Brand ###
PATCH http://localhost:8000/brand/98819620-647b-49f0-807a-7f45c93438a2
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
    "description":"this is updated withour name"
}

### Delete a brand ###

DELETE http://localhost:8000/brand/98819620-647b-49f0-807a-7f45c93438a2
Authorization: Bearer {{admin_token}}