@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxODIyZWQ4NC0wNWVkLTQwMmYtYmJhZS1jMTMyMzg2Yjc2M2QiLCJpYXQiOjE3NzIzNDE3ODAsImV4cCI6MTc3Mjk0NjU4MH0.X9lpbbYWUfUTwKk3lVKeuaRFVU-OmmdqRZt411yXM9w
@customer_token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGEzMjlhNi02ODE3LTQ0NWUtYTBmZi05NTJkOGVkZmY1YzAiLCJpYXQiOjE3NTk2Nzg1MjMsImV4cCI6MTc2MDI4MzMyM30.HTrbpWoFNl0I5Z6e2ZqcqI6QmkBH3qfMGXEcKDrnlNs

### Login as customer ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"test@gmail.com",
 "password":"test123"
}


### Login as Admin ###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
 "email":"admin@gmail.com",
 "password":"test123"
}


### Create a brand
POST http://localhost:8000/brand
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
    "name":"tango yankee",
    "description":"This is a test"
    
}


### Get all Brands ###
GET http://localhost:8000/brand

### Get a Brand ###
GET http://localhost:8000/brand/0cbed636-e7ff-44fe-8440-f186bf1a7e25


### Update a Brand ###
PATCH http://localhost:8000/brand/98819620-647b-49f0-807a-7f45c93438a2
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
    "description":"this is updated withour name"
}

### Delete a brand ###

DELETE http://localhost:8000/brand/18956c46-b573-47b4-b497-87d07f8f3b37
Authorization: Bearer {{admin_token}}